import pycinema
import pycinema.filters
import pycinema.theater
import pycinema.theater.views

# pycinema settings
PYCINEMA = { 'VERSION' : '2.0.0'}

# layout
vf0 = pycinema.theater.Theater.instance.centralWidget()
vf0.setHorizontalOrientation()
vf3 = vf0.insertFrame(0)
vf3.setVerticalOrientation()
vf3.insertView( 0, pycinema.theater.views.NodeEditorView() )
TableView_0 = vf3.insertView( 1, pycinema.theater.views.TableView() )
vf3.setSizes([414, 413])
vf1 = vf0.insertFrame(1)
vf1.setVerticalOrientation()
PlotView_0 = vf1.insertView( 0, pycinema.theater.views.PlotView() )
PlotView_2 = vf1.insertView( 1, pycinema.theater.views.PlotView() )
vf1.setSizes([414, 413])
vf2 = vf0.insertFrame(2)
vf2.setVerticalOrientation()
PlotView_1 = vf2.insertView( 0, pycinema.theater.views.PlotView() )
PlotView_3 = vf2.insertView( 1, pycinema.theater.views.PlotView() )
vf2.setSizes([414, 413])
vf0.setSizes([785, 786, 785])

# filters
CinemaDatabaseReader_0 = pycinema.filters.CinemaDatabaseReader()
TableQuery_0 = pycinema.filters.TableQuery()
PlotItems_0 = pycinema.filters.PlotItems()
PlotItems_1 = pycinema.filters.PlotItems()
PlotItems_2 = pycinema.filters.PlotItems()
PlotItems_3 = pycinema.filters.PlotItems()

# properties
CinemaDatabaseReader_0.inputs.path.set("data/plot.cdb", False)
CinemaDatabaseReader_0.inputs.file_column.set("FILE", False)
TableQuery_0.inputs.table.set(CinemaDatabaseReader_0.outputs.table, False)
TableQuery_0.inputs.sql.set("SELECT * FROM input", False)
PlotView_0.inputs.title.set("Fibonacci", False)
PlotView_0.inputs.background.set("white", False)
PlotView_0.inputs.plotitems.set(PlotItems_0.outputs.items, False)
PlotView_0.inputs.table.set(TableQuery_0.outputs.table, False)
PlotItems_0.inputs.x.set("a", False)
PlotItems_0.inputs.y.set("b", False)
PlotItems_0.inputs.line.set("default", False)
PlotItems_0.inputs.color.set("blue", False)
PlotItems_0.inputs.width.set(1.0, False)
PlotView_1.inputs.title.set("Plot Title", False)
PlotView_1.inputs.background.set("white", False)
PlotView_1.inputs.plotitems.set(PlotItems_1.outputs.items, False)
PlotView_1.inputs.table.set(TableQuery_0.outputs.table, False)
PlotItems_1.inputs.x.set("b", False)
PlotItems_1.inputs.y.set("c", False)
PlotItems_1.inputs.line.set("default", False)
PlotItems_1.inputs.color.set("black", False)
PlotItems_1.inputs.width.set(1.0, False)
PlotView_2.inputs.title.set("Red Line Plot", False)
PlotView_2.inputs.background.set("white", False)
PlotView_2.inputs.plotitems.set(PlotItems_2.outputs.items, False)
PlotView_2.inputs.table.set(TableQuery_0.outputs.table, False)
PlotItems_2.inputs.x.set("a", False)
PlotItems_2.inputs.y.set("c", False)
PlotItems_2.inputs.line.set("dash", False)
PlotItems_2.inputs.color.set("red", False)
PlotItems_2.inputs.width.set(2.0, False)
PlotView_3.inputs.title.set("Fibonacci Geen", False)
PlotView_3.inputs.background.set("white", False)
PlotView_3.inputs.plotitems.set(PlotItems_3.outputs.items, False)
PlotView_3.inputs.table.set(TableQuery_0.outputs.table, False)
PlotItems_3.inputs.x.set("a", False)
PlotItems_3.inputs.y.set("b", False)
PlotItems_3.inputs.line.set("default", False)
PlotItems_3.inputs.color.set("green", False)
PlotItems_3.inputs.width.set(2.0, False)
TableView_0.inputs.table.set(TableQuery_0.outputs.table, False)

# execute pipeline
CinemaDatabaseReader_0.update()
