from PySide6 import QtGui

Z_EDGE_LAYER = 400
Z_NODE_LAYER = 500

NODE_HEADER_HEIGHT = 20
NODE_BORDER_WIDTH = 5
# NODE_BORDER_RADIUS = 5
NODE_SEP_WIDTH = 5
NODE_WIDTH = 200
NODE_MARGIN = 3
NODE_SEP_Y = 25
NODE_PORT_Y = 35
NODE_PORT_SPACE = 25

PORT_SIZE = 8
PORT_BORDER_WIDTH = 2
# bright
# COLOR_BASE = QtGui.QColor('#d5d5d5')
# COLOR_NORMAL_ = '#000'

# dark
# COLOR_BASE = QtGui.QColor('#27292b')
COLOR_BASE = QtGui.QColor('#999')
COLOR_BASE_T = QtGui.QColor('#666')
COLOR_BASE_T.setAlpha(200)
COLOR_NORMAL_ = '#ddd'
COLOR_DISABLED_ = '#999'

COLOR_BACKGROUND = QtGui.QColor('#333438')
# COLOR_BACKGROUND = QtGui.QColor('#f00')
# COLOR_BASE = QtGui.QColor('#444')
# COLOR_BORDER = QtGui.QColor('#27292b')
COLOR_BORDER = QtGui.QColor('#ff0000')
COLOR_WIDGET = QtGui.QColor('#505050')

COLOR_RED = QtGui.QColor('#98281b')
COLOR_RED_T = QtGui.QColor('#98281b')
COLOR_RED_T.setAlpha(200)

COLOR_BLUE = QtGui.QColor('#15a3b4')
COLOR_BLUE_T = QtGui.QColor('#15a3b4')
COLOR_BLUE_T.setAlpha(200)

COLOR_NORMAL = QtGui.QColor(COLOR_NORMAL_)
