#!/usr/bin/env python

import pycinema.explorer
import argparse

helptext = "\n\
\n\
examples: \n\
\n\
  cinema some.cdb\n\
    run the \'view\' viewer on some.cdb\n\
"

# normal option parsing
parser = argparse.ArgumentParser( description="cinema: transform input data to cinema database",
                                  epilog=helptext,
                                  formatter_class=argparse.RawDescriptionHelpFormatter )

parser.add_argument( "--version", action="version", version=pycinema.__version__)

# positional argument
parser.add_argument( "filename", nargs='*' )

args = parser.parse_args()

# run  
pycinema.explorer.Explorer(" ".join([str(elem) for elem in args.filename]))

