name: QueryWriteTest

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test Environment
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install libglu1-mesa-dev xvfb
          python -m pip install pytest pytest-xvfb
      - name: Dependencies
        run: |
          python setup.py install
      - name: Test using ModernGL
        run: |
          python -m pytest -s testing/QueryWriteTest.py

  macos:
    strategy:
      matrix:
        python-version: [3.9]
        os-version: [macos-11, macos-12]

    runs-on: ${{ matrix.os-version }} 
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pytest
          python setup.py install
      - name: Test using ModernGL
        run: |
          python -m pytest -s testing/QueryWriteTest.py
