name: RenderTest

on:
  push:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test Environment
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install libglu1-mesa-dev xvfb
          python -m pip install pytest pytest-xvfb
      - name: Dependencies
        run: |
          python setup.py install
      - name: Test using ModernGL
        run: |
          python -m pytest -s testing/RenderTest.py

  macos11:
    runs-on: macos-11
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pytest
          python setup.py install
      - name: Test using ModernGL
        run: |
          python -m pytest -s testing/RenderTest.py

  macos12:
    runs-on: macos-12
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install pytest
          python setup.py install
      - name: Test using ModernGL
        run: |
          python -m pytest -s testing/RenderTest.py

  # windows:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       python-version: [3.9]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python ${{ matrix.python-version }}
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}
  #     - uses: msys2/setup-msys2@v2
  #       with:
  #         msystem: MINGW64
  #         release: false
  #         install: mingw-w64-x86_64-mesa
  #     - name: Test Environment
  #       shell: pwsh
  #       run: |
  #         $env:GLCONTEXT_WIN_LIBGL = "C:\msys64\mingw64\bin\opengl32.dll"
  #     - name: Dependencies
  #       run: |
  #         python setup.py install
  #     - name: Test using ModernGL
  #       run: |
  #         python -m pytest -s testing/RenderTest.py
